language: go

go:
  - "1.10"
  - 1.11
  - 1.12
  - 1.13
  - master

install:
  - go get -t ./...

script:
  - go build
  - go test -v ./...
  - go test -v -bench=.
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
